services:
  db:
    image: postgres:16
    container_name: fasting_db
    environment:
      POSTGRES_DB: fastingdb
      POSTGRES_USER: fasting_user
      POSTGRES_PASSWORD: fasting_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fasting_user -d fastingdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: fasting_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xms128m -Xmx512m"
    restart: unless-stopped

volumes:
  pgdata:
