services:
  - type: web
    name: fasting-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      # Connection-URL + Credentials aus der DB ziehen (gültige Properties!)
      - key: DATABASE_URL
        fromDatabase: { name: fasting-db, property: connectionString }
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase: { name: fasting-db, property: user }
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase: { name: fasting-db, property: password }
      - key: DB_NAME
        fromDatabase: { name: fasting-db, property: database }

      # Aus der DB-URL eine JDBC-URL bauen (Render-Interpolation mit $$)
      - key: JDBC_DATABASE_URL
        value: jdbc:$${DATABASE_URL}?sslmode=require

databases:
  - name: fasting-db
    plan: free
    region: frankfurt
    databaseName: fasting_app
    user: fasting_user
