services:
  - type: web
    name: fasting-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: fasting-db
          property: connectionString
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: fasting-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: fasting-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: fasting-db
          property: password

databases:
  - name: fasting-db
    databaseName: fasting_app
    user: fasting_user
