services:
  - type: web
    name: fasting-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        value: ifvQ24IWvnUOrXCY80uu5jEy1kijIHr2EP0rToUI5Wg89r1j7m-3xe72p8a00UNr
      - key: DATABASE_URL
        fromDatabase:
          name: fasting-db
          property: connectionString
      # Protect Swagger UI with Basic Auth (credentials stored as Render secrets)
      - key: SWAGGER_BASIC_ENABLED
        value: "true"
      - key: SWAGGER_BASIC_USER
        sync: false
      - key: SWAGGER_BASIC_PASS
        sync: false
      # Optional second factor for Swagger (header X-2FA required when enabled)
      - key: SWAGGER_2FA_ENABLED
        value: "false"
      - key: SWAGGER_2FA_CODE
        sync: false
      # Real TOTP-based 2FA (Google Authenticator). If set, X-2FA must carry a valid 6-digit code.
      - key: SWAGGER_TOTP_SECRET
        sync: false

databases:
  - name: fasting-db
    plan: free
    region: frankfurt
    databaseName: fasting_app
    user: fasting_user
