services:
  - type: web
    name: fasting-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        value: ifvQ24IWvnUOrXCY80uu5jEy1kijIHr2EP0rToUI5Wg89r1j7m-3xe72p8a00UNr

databases:
  - name: fasting-db
    plan: free
    region: frankfurt
    databaseName: fasting_app
    user: fasting_user
