server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://db:5432/fastingdb
    username: fasting_user
    password: fasting_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
