#!/bin/bash
# Frontend Development Helper - Quick API Tests

echo "🚀 Frontend Development API Helper"
echo "=================================="
echo ""

BASE_URL="http://localhost:8080"

echo "📋 Available API Endpoints:"
echo ""
echo "1. Health Check:"
echo "   GET $BASE_URL/actuator/health"
echo ""
echo "2. Check Username Availability:"
echo "   GET $BASE_URL/api/users/check-availability?username=YOUR_USERNAME"
echo "   GET $BASE_URL/api/users/check-availability?username=USER&email=EMAIL"
echo ""
echo "3. Register/Login User:"
echo "   POST $BASE_URL/api/users/login-or-create"
echo "   Body: {\"username\":\"YOUR_USERNAME\",\"email\":\"YOUR_EMAIL\"}"
echo ""
echo "4. Find User by Identifier:"
echo "   GET $BASE_URL/api/users/find/USERNAME_OR_EMAIL"
echo ""

echo "🔧 Quick Test Commands:"
echo ""
echo "# Test if API is running"
echo "curl $BASE_URL/actuator/health"
echo ""
echo "# Check if username is available"
echo "curl '$BASE_URL/api/users/check-availability?username=myuser'"
echo ""
echo "# Create new user"
echo "curl -X POST $BASE_URL/api/users/login-or-create \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"username\":\"myuser\",\"email\":\"myuser@example.com\"}'"
echo ""

echo "📁 Available Test Scripts:"
echo ""
echo "  ./test-api.sh              - Run all tests"
echo "  ./scripts/test-health.sh   - Test health endpoint"
echo "  ./scripts/test-availability.sh [username] - Test availability"
echo "  ./scripts/test-create-user.sh [username] [email] - Create user"
echo "  ./scripts/test-duplicate.sh [username] - Test duplicate prevention"
echo "  ./scripts/test-scenarios.sh - Test your specific scenarios"
echo ""

echo "💡 Example Usage:"
echo "  ./scripts/test-availability.sh myuser"
echo "  ./scripts/test-create-user.sh john john@example.com"
echo "  ./scripts/test-scenarios.sh"
echo ""
